### ISSUE TITLE
Deprecate full image

### ISSUE THREAD

**Issue by viceice** [renovatebot/docker-renovate#15]
We should deprecate the full image, as it would become very huge over time.

For supporting flutter, we need to add the flutter sdk (500 MB tar.xz, 1.5GB extracted). 

Steps:
- [ ] no longer preinstall new sdk's to full image
- [ ] add samples for selfhosting for adding need sdks
- [ ] remove full image

**Comment by rarkins** [comment]
Here's what I'd like:

1. Have a separate Dockerfile just for building the "slim" image. Long term this is the only one that we publish.

2. Make the "full" (i.e. `latest`) image be based off the slim image, and *really* simple so that people can copy/paste it and not have to keep checking back regularly for changes. Maybe a simple and separate repo (e.g. `renovatebot/docker-renovate-full`).

3. Stop adding new SDKs to the full image now, but still add them to the install-tool and add commented-out instructions for each of them even if we don't install them.

4. (eventually) Stop publishing the full image altogether but have a *reference* repo showing how to build the full image.

What do you think?

**Comment by viceice** [comment]
👍 that's what I'm mean.

**Comment by rarkins** [comment]
If our goal is that people build/maintain their own Renovate image with preferred SDKs, we should aim for this:
- Show how to build and publish using GitHub Actions + Packages as well as (separately) GitLab Pipelines + Registry
- Set it up to automatically keep both Renovate as well as SDKs up-to-date using Renovate

**Comment by rarkins** [comment]
So should I create `renovatebot/docker-renovate-full` in preparation for separating it out from the slim image?

**Comment by viceice** [comment]
Sure

**Comment by crazy-max** [comment]
Hi,

I have a Jenkins job to scan repos with `renovate/renovate:19` full image. Today when Jenkins has pulled this image, the resulted renovate version is `19.221.0-slim` instead of the full version.
Would have been nice to handle backward compatibility and so create a `renovate/renovate:19-slim` instead.

**Comment by crazy-max** [comment]
Ok looks like this is only an issue with the `org.opencontainers.image.version`. So you should overwrite this label in the full version on https://github.com/renovatebot/docker-renovate-full
